### ISSUE TITLE
onboarding 画面に猫のアニメーションを追加する

### ISSUE THREAD

**Issue by Tani1015** [Tani1015/flutter_hackason_template#3]
##  変更内容
`save the cat` というタイトルの上部に猫のアニメーションを追加する

追加する猫のアニメーションは `cat.json`

**Comment by GichanMinsu** [comment]
<img width="616" alt="image" src="https://github.com/user-attachments/assets/9979f62e-6e6f-4c1e-92a5-a700c62b91d9">

ダークモードの場合、尻尾が見えない大丈夫でしょうか？

**Comment by GichanMinsu** [comment]
PRに書きましたが、ネコのJsonだけ色修正すればいいので、PRを先にいたしました。よろしくおくお願いします。🙇

**Comment by Tani1015** [comment]
ダークモードで背景色と被る場合は仕方ないので問題ないです👍
背景色が被る場合の対象方としては猫の背景に異なる色で円を作成するなどデザインの一部として背景色を変更することです
